### ISSUE TITLE
Does `onMouseUp` work correctly?

### ISSUE THREAD

**Issue by foxCanFly** [gribnoysup/react-yandex-maps#47]
Hello!
Is it a normal if I click on the map `onMouseUp` is triggered but if after click I move a cursor then nothing will happen(event won't triggered at all)..?

**Comment by gribnoysup** [comment]
Hi @foxCanFly! 

If I understand the flow of your actions correctly, then yes, this is pretty normal for DOM events in general 😸 When you press the mouse button and then move the mouse away from the map, the `mouseup` event happens on the other element, but not on the map (because the mouse cursor is not over map anymore)

Just to clarify: all event handlers in this library are passed straight to the Yandex maps API event system, so if there is something not working correctly, it is probably on their side 😉 Still, feel free to open an issue here if you are not sure.

I feel that the issue could be closed, but again, feel free to add comments, if you still have questions!

**Comment by mmarkelov** [comment]
@foxCanFly К дополнению ответа скажу, если тебе надо отлавливать моменты движения карты можно использовать 'actionbegin', примерно так:
`<Map instanceRef={ref => {
				ref.events.add('actionbegin', () => {
						console.log('Событие на карте');
					});
				}}>`
В таком случае будут тригерриться события по движению по карте.
Дополнительно можно посмотреть тут(раздел События): [https://tech.yandex.ru/maps/doc/jsapi/2.1/ref/reference/Map-docpage/](url)
