### ISSUE TITLE
Is it possible to avoid flickering on re-render on props change?

### ISSUE THREAD

**Issue by il-tmfv** [gribnoysup/react-yandex-maps#52]
I have an array of points to render on a map. If I change it in some way (for example, change property of one point object that is used for marking currently active placemark) map gets re-rendered and I see flickering.
Is there any way to avoid it?

**Comment by il-tmfv** [comment]
Simple code example:
```js
<YMaps>
  <Map>
     <Clusterer>
        {this.renderPlaceMarks(points, defaultOpts)}
     </Clusterer>
  </Map>
</YMaps>
```
`renderPlaceMarks` basically returns array of `<Placemark />`'s, and it changes according to `points` array objects properties.

**Comment by gribnoysup** [comment]
Hi @il-tmfv!

Unfortunately, I can't reproduce the issue you are encountering. 

Here is a code sandbox with a bunch of `Placemark`s inside `Clusterer` that are switching both options and properties of the Placemark when you press `+` button: https://codesandbox.io/s/o1l3ry0j75. No flickering is happening there. 

Any chance you can provide a reproduction example? Otherwise, I don't think I can help :/

**Comment by il-tmfv** [comment]
Yeap, I see. I have double checked project. Problem was with mobx.
Sorry for bothering :(

**Comment by al4str** [comment]
@il-tmfv, having flickering too (and use mobx in my project). How did you solved your problem?

**Comment by il-tmfv** [comment]
@al4str, sorry, it's really hard to remember right now how I fixed this. But I can give you a tip: try to add/remove `@observer` decorators from components in a component's tree. It is also good to keep any state changing logic outside of component's lifecycle methods.
Also I remember that I saved refs to all placemarks (see #50). I did it for emulating clicks from outside the map, but maybe it was also a part of solution.
